# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(953, 642)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(5, 10, 130, 23))
        self.btn_open.setObjectName("btn_open")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(5, 40, 130, 23))
        self.btn_next.setObjectName("btn_next")
        self.btn_pre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pre.setGeometry(QtCore.QRect(5, 70, 130, 23))
        self.btn_pre.setObjectName("btn_pre")
        self.btn_undo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_undo.setGeometry(QtCore.QRect(5, 100, 130, 23))
        self.btn_undo.setObjectName("btn_undo")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(5, 130, 130, 23))
        self.btn_save.setObjectName("btn_save")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(150, 10, 780, 591))
        self.tabWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_manu = QtWidgets.QWidget()
        self.tab_manu.setObjectName("tab_manu")
        self.tabWidget.addTab(self.tab_manu, "")
        self.tab_semi = QtWidgets.QWidget()
        self.tab_semi.setObjectName("tab_semi")
        self.label_rgb_semi = QtWidgets.QLabel(self.tab_semi)
        self.label_rgb_semi.setGeometry(QtCore.QRect(30, 150, 320, 240))
        self.label_rgb_semi.setObjectName("label_rgb_semi")
        self.label_mask_semi = QtWidgets.QLabel(self.tab_semi)
        self.label_mask_semi.setGeometry(QtCore.QRect(430, 150, 320, 240))
        self.label_mask_semi.setObjectName("label_mask_semi")
        self.label_curmarker_semi = QtWidgets.QLabel(self.tab_semi)
        self.label_curmarker_semi.setGeometry(QtCore.QRect(90, 540, 141, 16))
        self.label_curmarker_semi.setObjectName("label_curmarker_semi")
        self.tabWidget.addTab(self.tab_semi, "")
        self.tab_auto = QtWidgets.QWidget()
        self.tab_auto.setObjectName("tab_auto")
        self.label_rgbtfusion_auto = QtWidgets.QLabel(self.tab_auto)
        self.label_rgbtfusion_auto.setGeometry(QtCore.QRect(5, 40, 768, 192))
        self.label_rgbtfusion_auto.setObjectName("label_rgbtfusion_auto")
        self.label_registered_auto = QtWidgets.QLabel(self.tab_auto)
        self.label_registered_auto.setGeometry(QtCore.QRect(40, 290, 320, 240))
        self.label_registered_auto.setObjectName("label_registered_auto")
        self.label_mask_auto = QtWidgets.QLabel(self.tab_auto)
        self.label_mask_auto.setGeometry(QtCore.QRect(410, 290, 320, 240))
        self.label_mask_auto.setObjectName("label_mask_auto")
        self.label = QtWidgets.QLabel(self.tab_auto)
        self.label.setGeometry(QtCore.QRect(90, 10, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_auto)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_auto)
        self.label_3.setGeometry(QtCore.QRect(600, 10, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_auto)
        self.label_4.setGeometry(QtCore.QRect(120, 260, 160, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_auto)
        self.label_5.setGeometry(QtCore.QRect(530, 260, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.tab_auto)
        self.label_11.setGeometry(QtCore.QRect(90, 540, 59, 15))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_curmarker_auto = QtWidgets.QLabel(self.tab_auto)
        self.label_curmarker_auto.setGeometry(QtCore.QRect(90, 540, 141, 16))
        self.label_curmarker_auto.setObjectName("label_curmarker_auto")
        self.tabWidget.addTab(self.tab_auto, "")
        self.label_img_info = QtWidgets.QLabel(self.centralwidget)
        self.label_img_info.setGeometry(QtCore.QRect(5, 160, 130, 40))
        self.label_img_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_img_info.setObjectName("label_img_info")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(5, 200, 140, 401))
        self.treeView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.treeView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(True)
        self.radio_rect = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_rect.setGeometry(QtCore.QRect(350, 12, 81, 21))
        self.radio_rect.setObjectName("radio_rect")
        self.radio_poly = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_poly.setGeometry(QtCore.QRect(440, 12, 73, 21))
        self.radio_poly.setObjectName("radio_poly")
        self.label_log = QtWidgets.QLabel(self.centralwidget)
        self.label_log.setGeometry(QtCore.QRect(520, 12, 400, 21))
        self.label_log.setObjectName("label_log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_open.setText(_translate("MainWindow", "open dir"))
        self.btn_next.setText(_translate("MainWindow", "next image"))
        self.btn_pre.setText(_translate("MainWindow", "pre image"))
        self.btn_undo.setText(_translate("MainWindow", "undo"))
        self.btn_save.setText(_translate("MainWindow", "save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_manu), _translate("MainWindow", "全手动"))
        self.label_rgb_semi.setText(_translate("MainWindow", "TextLabel"))
        self.label_mask_semi.setText(_translate("MainWindow", "TextLabel"))
        self.label_curmarker_semi.setText(_translate("MainWindow", "current_marker:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_semi), _translate("MainWindow", "半自动"))
        self.label_rgbtfusion_auto.setText(_translate("MainWindow", "RGB_T_Fusion"))
        self.label_registered_auto.setText(_translate("MainWindow", "Registered"))
        self.label_mask_auto.setText(_translate("MainWindow", "Mask"))
        self.label.setText(_translate("MainWindow", "RGB"))
        self.label_2.setText(_translate("MainWindow", "Thermal"))
        self.label_3.setText(_translate("MainWindow", "Fusion"))
        self.label_4.setText(_translate("MainWindow", "配准后的红外"))
        self.label_5.setText(_translate("MainWindow", "掩码标注"))
        self.label_curmarker_auto.setText(_translate("MainWindow", "current_marker:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_auto), _translate("MainWindow", "全自动"))
        self.label_img_info.setText(_translate("MainWindow", "image_info"))
        self.radio_rect.setText(_translate("MainWindow", "rectangle"))
        self.radio_poly.setText(_translate("MainWindow", "polygon"))
        self.label_log.setText(_translate("MainWindow", "TextLabel"))

